[programs.localnet]
ido_pool = "FvsasXFPtyEcGv7cRqutXAydR54DGiR3p3ohjqjn7F8Z"

[programs.devnet]
ido_pool = "FvsasXFPtyEcGv7cRqutXAydR54DGiR3p3ohjqjn7F8Z"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "mocha -t 20000 tests/ido-pool.js"
